import esbuild from 'esbuild';
import process from 'process';
import { copyFileSync } from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// The Obsidian submission bot reads manifest.json at the repository ROOT.
	// Sync plugin/manifest.json (and versions.json) to the parent directory on
	// every production build so the root copies never drift.
	copyFileSync('manifest.json', '../manifest.json');
	copyFileSync('versions.json', '../versions.json');
	process.exit(0);
} else {
	await context.watch();
}